### ISSUE TITLE
TRestDetectorReadoutAnalysisProcess should reject events?

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/detectorlib#121]
Hi!

Just wondering if an analysis process should reject events. It seems that `TRestDetectorHitsReadoutAnalysisProcess` is rejecting the events if no energy deposits are found.

Perhaps the process should add a warning

```
this->SetWarning("Hits with no energy deposits were found. Events were rejected");
``` 

or 

```
this->SetError("Hits with no energy deposits were found. Events were rejected");
``` 

When one opens the ROOT run file then will be prevented that there are some processes that produced errors.

OR, perhaps we should have a dedicated process to reject events `TRestDetectorReadoutFiducialization` and let the readoutAnalysis just add new variables to the analysisTree.

**Comment by lobis** [comment]
> `TRestDetectorHitsReadoutAnalysisProcess`

This process by default does not remove any events, it's only if the `removeZeroEnergyEvents` is set to `true` when this happens (defaults to `false`).
