### ISSUE TITLE
Implement W gas parameter inside TRestDetectorGas directly at the time of gas file generation

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/detectorlib#18]
This issue is connected with the following discussion at the forum

http://rest-forum.unizar.es/t/obsolete-or-duplicated-gas-definitions/508

Ideally we would fix the value of W (average ionization potential of the molecules inside the gas mixture) at the time of gas generation. Actually this value is given at the RML, and many values at the server https://sultan.unizar.es/gasFiles/gases.rml contain wrong values.

Therefore, the best would be that we do not define manually `W` at the RML, but its value is calculated and registered directly at the associated `TRestDetectorGas` metadata member.

The calculation could be done for example using the table proposed at the forum by @cmargalejo 

https://pdg.lbl.gov/2019/reviews/rpp2019-rev-particle-detectors-accel.pdf

![image-2](https://user-images.githubusercontent.com/12447509/128703589-01c61d34-d241-4fd2-a4a5-8cecd72e63b2.png)

**Comment by lobis** [comment]
- https://github.com/rest-for-physics/detectorlib/pull/113

In the PR above we implemented extraction of `W` and Fano factor from the gas, but requires Garfield to be installed.
