### ISSUE TITLE
Compiling with the latest garfield

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/detectorlib#4]
I find that in the latest garfield, the file ComponentBase.hh is renamed to Component.hh. 

https://gitlab.cern.ch/garfield/garfieldpp/-/commit/4b72c508aa6e80462683b216f4f0149c1b44ed37

Could there be some problem compiling TRestDetectorGeometry?

**Comment by jgalan** [comment]
RIght, that will be an issue, do Garfield++ use any versioning system so that we could say if GARFIELD > X version do something?

If not, do we really need to give support for the latest Garfield?

**Comment by nkx111** [comment]
I cannot find any versioning system in the code of garfield++.
There is a possible workaround to support latest Garfield. It is by including "ComponentConstant.h" instead of "ComponentBase.h", and add a preprocessor like: 

```
#if defined G_COMPONENT_H
#define ComponentBase Component
#endif
```

That makes ComponentBase defined again for the latest version.

**Comment by lobis** [comment]
https://github.com/rest-for-physics/detectorlib/pull/34 introduced changes that should make the code compatible with old and new versions of Garfield, via preprocessor directives. I haven't thoroughly tested it with old versions though but it should work as before.
