### ISSUE TITLE
Reversed Fano factor?

### ISSUE THREAD

**Issue by ufan** [rest-for-physics/detectorlib#73]
https://github.com/rest-for-physics/detectorlib/blob/49d34c93bca31afb0a3d88db187f189ee38d6a2c/src/TRestDetectorHitsSmearingProcess.cxx#L89

Hi, guys, I can't understand this smearing design.
Should not it be (the fano factor):
    Double_t eRes = fResolutionAtERef * TMath::Sqrt( eDep / fEnergyRef ) / 2.35 / 100.0;

Current implementation means the same FWHM for any value of enery deposit. Is it designed to behave like this?

**Comment by jgalan** [comment]
Hi! Yes, it is designed to be as simple as creating an artificial smearing where the final result will produce an smeared spectra with the width of each peak in the spectrum proportional to the value introduced by the user.

So, it is a way to introduce the final energy resolution observed, including all the effects, fano factor, avalancha amplification, electronic noise, etc.



So, for each event, each energy deposit is rescaled by the same value, but this is randomised between different events.

I recently updated the documentation of this process: https://github.com/rest-for-physics/detectorlib/pull/72

https://sultan.unizar.es/test/classTRestDetectorHitsSmearingProcess.html

I think for introducing more details we would need to introduce a more sophisticated process, perhaps using Garfield. However, this simple process is also convenient for saving computational cost.

It exists a [TRestDetectorGarfieldDriftProcess](https://sultan.unizar.es/rest/TRestDetectorGarfieldDriftProcess_8cxx_source.html) But it is a long time ago it has not been used.
